version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    reviewers:
      - "nilselvefors"
    labels:
      - "dependencies"
      - "npm"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    reviewers:
      - "nilselvefors"
    labels:
      - "dependencies"
      - "npm"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    reviewers:
      - "nilselvefors"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "*"
